### ISSUE TITLE
Categories Type similar to Tags

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#59] opened 2015-09-17 07:08 UTC
Hi I was wondering if it would be beneficial to have a categories property similar to tags.

I used this:
[Property("Categories")]
public virtual CollectionProperty<StringProperty> Categories { get; set; }

But it doesn't have the same easiness of using tags where you can comma separate the list in the UI

**Comment by fschultz** [comment] 2015-09-17 15:57
If you want you can use the `TagProperty` for categories also. The important thing is to set the `TagContext` to something unique for the categories. That way they will be held separate from the rest of the tag properties (even on the same page).

```
    [TagProperty("Categories", TagContext = "category")]
    public virtual TagProperty Categories { get; set; }
```

**Comment by dotnetshadow** [comment] 2015-09-18 00:36
Thanks for the information could you please tell me a little more about TagContext 
/// The tag property enable tags for a particular page type. Notice that you can
/// use multiple tag spaces for the same page by setting different tag contexts.
 /// Be sure to use [TagProperty] to define the TagContext, otherwise it will
 /// fallback to the standard tag space.

Does that mean that a page by default has a Tag property, but you can set other tag type properties as long as a context is associated with it?

**Comment by dotnetshadow** [comment] 2015-09-18 03:02
I just tried the above but I get the following error when I try to add a new article page type

 An item with the same key has already been added.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentException: An item with the same key has already been added.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[ArgumentException: An item with the same key has already been added.]
   System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) +56
   System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) +13754233
   KalikoCMS.Core.TagManager.GetTagContext(String contextName) +213
   KalikoCMS.Core.TagManager.TagPage(Guid pageId, String contextName, IEnumerable`1 tags) +47
   KalikoCMS.PropertyType.TagProperty.PageSaved(CmsPage page) +53
   KalikoCMS.Core.EditablePage.Save() +4611
   KalikoCMS.Admin.Content.EditPage.SavePropertiesForPage(EditablePage editablePage) +687
   KalikoCMS.Admin.Content.EditPage.SaveDataForNewPage() +85
   KalikoCMS.Admin.Content.EditPage.PublishButtonEventHandler(Object sender, EventArgs e) +54
   System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) +143
   System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) +148
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3360

**Comment by fschultz** [comment] 2015-09-18 04:08
`TagContext` is a way to separate "tag clouds" so that you for instance can list all tags that are used for categories without getting any other tags from the system. This also works for tag suggestions when editing the property. If no `TagContext` is set in the property attribute the default context will be used. All pages needs to have a tag property added in order to use it.

Your code looks correct and when I tested it here it worked until I tried to add a tag that was named exact the same as another tag in another context. Could this be what caused your error as well?

I'm escalating this issue to a bug and will try to have it fixed in the next release.

**Comment by dotnetshadow** [comment] 2015-09-18 04:28
Actually in my case I just didn't fill in the tag at all I just left it blank, so maybe it's the same issue?

**Comment by fschultz** [comment] 2015-09-18 04:34
Yes, just noticed that it occurs regardless of the tags entered from the second save and on-wards. Will prioritize this before the features for 1.1.0.

**Comment by dotnetshadow** [comment] 2015-09-18 04:35
That is awesome, because once the error occurs I actually cannot add anymore pages, basically I can Select the page type but after that it throws that error

**Comment by fschultz** [comment] 2015-09-18 04:40
Found the issue and will update the code. As a work-around until the next release you can change the `TagContext` to use lower case only:

```
[TagProperty("Tags", TagContext = "articletag")]
public virtual TagProperty Tags { get; set; }

[TagProperty("Categories", TagContext = "articlecategory")]
public virtual TagProperty Categories { get; set; }
```

The problem is that internally the in-memory storage uses lowercase names only.

**Comment by dotnetshadow** [comment] 2015-09-18 04:50
Excellent work I can confirm that does in fact solve the problem.

The only issue was I had start again because existing tags mixed casing were still in the database so I guess until you push the fix those will always cause this error

**Comment by fschultz** [comment] 2015-09-18 05:01
Unfortunately the workaround will only affect the system so that this issue won't arise again. Therefore a couple of manual steps are needed in projects that already have multiple tag contexts written to the database with the same name.

* Open the database
* Check the `TagContext` table to see what `TagContextId` is assigned to the duplicate tag contexts
* Open `Tag` table to see what tags are connected to the `TagContextId` from the previous step
* Delete all posts in `PageTag` that are connected to the `TagId` from the previous step
* Delete the posts from `Tag` that are connected to the duplicate contexts
* Delete the duplicate contexts in `TagContext`

Be sure to recompile the project after these changes are made since there's some caching involved in the tag manager.

(If using the SQLite a good editor is http://www.sqliteexpert.com/)

**Closed** 2015-12-13 10:50 UTC
Labels: bug, done
