### ISSUE TITLE
Invalid GUID or Null Object issue (1.0.0-beta3)

### ISSUE THREAD

**Issue by EdSF** [KalikoCMS/KalikoCMS.Core#48] opened 2015-08-13 15:51 UTC
Versions: `1.0.0-beta3`, Search `v.1.0.0-beta`:

CMS Admin Add Page:

1. If fresh install (no pages), you can't really add a new page....
 - if you don't select `Root` and try to add a new page:

   ` [FormatException: Unrecognized Guid format.]
   System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result) +12192041
   System.Guid..ctor(String g) +105
   KalikoCMS.Admin.Content.Dialogs.SelectPagetypeDialog.Page_Load(Object sender, EventArgs e) +110
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +85
   System.Web.UI.Control.OnLoad(EventArgs e) +79
   System.Web.UI.Control.LoadRecursive() +130
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2832`

 - if you select `Root` and try to add page

     `[NullReferenceException: Object reference not set to an instance of an object.]
   KalikoCMS.Admin.Content.Dialogs.SelectPagetypeDialog.Page_Load(Object sender, EventArgs e) +250
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +85
   System.Web.UI.Control.OnLoad(EventArgs e) +79
   System.Web.UI.Control.LoadRecursive() +130
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2832`

2. If you have existing pages:
 - You "have to" select an existing page and `Add Page` (making it a child of that page), then "move" (works great btw!) to be child of `Root`. 
 - If you try to Add to `Root`, same issue as above `NullReferenceException`.

I will tinker some more and try to obtain more detail....

**Comment by fschultz** [comment] 2015-08-13 18:03
Thank you very much for another exemplary bug report :) 

I don't know how I could have missed this one, but I've just committed a fix to the 1.0.0-rc1-branch that will allow pages to be created under the root.

This was caused by the new feature that can be used to limit which page types that are available based on the parent page. But the root page and no root/page selected was unhandled and led to the Guid / null reference errors.

**Comment by EdSF** [comment] 2015-08-13 23:02
Cool beans :+1: 

My "fix" (hack really) was:

    //Set "Root" as "default" - cases where no selection is made on front end
    Guid pageId;
    Guid.TryParse(Request.QueryString["pageId"], out pageId);

    var parent = PageFactory.GetPage(pageId);

    //null if parent is "Root" 
    var parentPageType = pageTypes.Find(p => p.PageTypeId == parent.PageTypeId);
   
    //add null check
    var allowAll = parentPageType == null || parentPageType.AllowedTypes == null;

    //add null check
    if (parentPageType != null && (parentPageType.AllowedTypes != null && parentPageType.AllowedTypes.Length == 0))
    ....

Good to learn about `SiteSettings` ! Thank you!

**Comment by fschultz** [comment] 2015-08-14 05:22
Was really nice to see the first pull request for the project that wasn't mine! Thanks :)

I've packaged and published RC1, which hopefully is stable enough to make the final 1.0.0. Meanwhile I will focus on bringing the documentation up to date.

**Comment by EdSF** [comment] 2015-08-14 13:57
Coming from `TFS` and `Mercurial`, am wrestling a little bit with `Git` (Windows and within VS) and that pull request (I think I deleted it) was likely me clicking on some button here in Github UI...

I think I'll stick to command line this point forward..sorry about that....

**Comment by fschultz** [comment] 2015-08-15 05:25
No problem, maybe next pull request will be intentional :) It took me a while to get into `Git` (being used to `TFS` and `Subversion`), especially the GitHub flavor. But nowadays I kind of prefer it in many ways.

**Closed** 2015-08-20 04:30 UTC
Labels: bug
